### ISSUE TITLE
Not pulling all comments

### ISSUE THREAD

**Issue by danharasymiw** [salt-today/salttoday#7]
Articles can have too many comments on them. When this happens you have to click load more. A parameter can be added to the url we use to scrape comments to change the amount of comments we get by default. This should be set to a higher number so we get all the comments.

Additionally, sometimes a comment can have too many responses and gets a similar load more button to view the responses. This doesn't happen a terrible amount of times, but it'd be nice to also get those comments too.

**Comment by xTVaser** [comment]
This is now resolved in all cases except #105
